name: Update cc tools

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
    secrets:
      github_access_token:
        required: true
      pip_ssh_key:
        required: true

jobs:
  update_cc_tools:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Pip SSH Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.pip_ssh_key }}

      - name: Install dependencies
        run: npm install renovate

      - name: Trigger renovate manually to evalute cc-tool packages
        run: npx renovate --token ${{ secrets.github_access_token }} satoshiking/${{ inputs.repo_name }}  # TODO(satoshiking)  change OWNER
